# This is a auto publish to npm workflow

name: Auto publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get package version
        run: echo "target ver [$TARGET_VERSION]"
        env:
          TARGET_VERSION: ${{ echo $GITHUB_REF | cut -d "/" -f3 }}
        
      - name: Change package version
        run: yarn version --new-version $TARGET_VERSION
        
      - name: Show
        run: yarn version
