# This is a auto publish to npm workflow

name: Auto publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get package version
        id: github-ref
        run: echo "::set-output name=tag::$(echo $TAG_REF | awk -F/ '{print $3}')"
        env:
          TAG_REF: ${{ github.ref }}
          
      - name: Show version
        run: echo "tag [$TARGET_VERSION]" && yarn version --new-version $TARGET_VERSION
        env:
          TARGET_VERSION: ${{ step.github-ref.outputs.tag }}
        
      - name: Show
        run: yarn version
