# This is a auto publish to npm workflow

name: Auto publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get package version
        run: TARGET_VERSION=`echo $TAG_REF | awk -F/ '{print $3}'` && echo $TARGET_VERSION
        env:
          TAG_REF: ${{ github.ref }}
          
      - run: echo "tag [$TARGET_VERSION] | ${TAGET_VERSION} | $TAG_REF | ${TAG_REF}"
        
      - name: Change package version
        run: yarn version --new-version $TARGET_VERSION
        
      - name: Show
        run: yarn version
