# This is a auto publish to npm workflow

name: Auto publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Change package version
        run: echo "$GITHUB_REF"
        
      - name: Change package version
        run: yarn version --new-version $GITHUB_REF

      - name: Install Dependencies
        run: yarn
        
      - name: Show
        run: yarn version
